name: Manual destroy

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      targetEnv:
        type: choice
        description: 'targetEnv'
        default: 'd1'
        required: true
        options:
          - d1
          - d2
          - t3
          - u1
          - prod
      #microSvcName:
      #  type: choice
      #  description: 'microSvcName'
      #  default: 'microa'
      #  required: true
      #  options:
      #    - microa
      #    - animal

jobs:
  buildDockerImage:
    name: manual destroy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials - d1
        if: ${{ inputs.targetEnv }} == 'd1'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.WENDYADMIN_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.WENDYADMIN_SECRET_KEY }}
          aws-region: 'us-east-1'
      - name: Configure AWS Credentials - d2
        if: ${{ inputs.targetEnv }} == 'd2'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.D2_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.D2_SECRET_KEY }}
          aws-region: 'us-east-1'
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: "16"
      - name: Install AWS CDK
        run: 'sudo npm install -g aws-cdk'
      - name: Destroy AWS resources
        run: |
          cd cdk-infra
          npm install
          npm run build
          cdk bootstrap
          cdk destroy --all --force
        env:
          targetEnv: ${{ inputs.targetEnv }}
          #microSvcName: ${{ inputs. microSvcName }}

          



        
      
      
      
