name: Manual init AWS Config OpenID Connect

on:
  workflow_dispatch:
    inputs:
      awsAccessKey:
        description: 'awsAccessKey'
        required: true
      awsSecretKey:
        description: 'awsSecretKey'
        required: true

jobs:
  setupAwsO:
    name: manual set up OpenID Connect
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials - d1
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ inputs.awsAccessKey }}
          aws-secret-access-key: ${{ inputs.awsSecretKey }}
          aws-region: 'us-east-1'
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: "16"
      - name: Install AWS CDK
        run: sudo npm install -g aws-cdk
      - name: Deploy to AWS
        run: |
          cd cdk-init-oidc
          npm install
          npm run build
          cdk bootstrap
          cdk deploy ---require-approval never


          



        
      
      
      
