name: Manual create ECR repo

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      microserviceName:
        type: choice
        description: 'microserviceName'
        default: 'microA'
        required: true
        options:
          - microA
          - microB

jobs:
  buildDockerImage:
    name: Create AWS ECR repo for a microservice
    runs-on: ubuntu-latest
    steps:
      - name: Set env var of ECR repo name
        run: |
          # repository name has to be lower case, https://github.com/docker/build-push-action/issues/37
          echo dockerRepoName=$(echo ${{ github.event.inputs.microserviceName }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.WENDYADMIN_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.WENDYADMIN_SECRET_KEY }}
          aws-region: 'us-east-1'
      - name: create ECR repo on AWS
        run: |
          aws ecr delete-repository --repository-name ${{ env.dockerRepoName }}

          
