name: Manual deploy

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      targetEnv:
        type: choice
        description: 'targetEnv'
        default: 'd1'
        required: true
        options:
          - d1
          - d2
          - d3
          - d4
          - d5
          - t1
          - t3
          - u1
      microSvcName:
        type: choice
        description: 'microSvcName'
        default: 'microa'
        required: true
        options:
          - microa
          - animal

jobs:
  buildDockerImage:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.WENDYADMIN_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.WENDYADMIN_SECRET_KEY }}
          aws-region: 'us-east-1'
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: "16"
      - name: Install AWS CDK
        run: 'sudo npm install -g aws-cdk'
      - name: Deploy to AWS
        run: |
          cd cdk-infra
          npm install
          npm run build
          cdk bootstrap
          cdk destroy --all --require-approval never
        env:
          targetEnv: ${{ inputs.targetEnv }}
          microSvcName: ${{ inputs. microSvcName }}

          



        
      
      
      
