name: Manual destroy ECR repo

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      microSvcImageRepo:
        type: choice
        description: 'microserviceName'
        default: 'microa-repo'
        required: true
        options:
          - microa-repo
          - microb-repo

jobs:
  buildDockerImage:
    name: Create AWS ECR repo for a microservice
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.WENDYADMIN_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.WENDYADMIN_SECRET_KEY }}
          aws-region: 'us-east-1'
      - name: create ECR repo on AWS
        run: |
          aws ecr delete-repository --repository-name ${{ github.event.inputs.microSvcImageRepo }} --force

          
